[package]
name = "analysis"
edition = "2024"
version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
ropey.workspace = true
rustc-hash.workspace = true
serde = { workspace = true, features = ["derive"] }
tree-sitter.workspace = true
tree-sitter-r.workspace = true

[dev-dependencies]
fixtures = { path = "../fixtures" }
itertools.workspace = true
serde_json.workspace = true
