[package]
name = "differential"
edition = "2024"
version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/differential.rs"

[dependencies]

[dev-dependencies]
analysis-legacy = { path = "../analysis-legacy" }
format = { path = "../format" }
ide = { path = "../ide" }
ropey.workspace = true
roughly-legacy = { path = "../roughly-legacy" }
semantics = { path = "../semantics" }
syntax = { path = "../syntax" }
