[workspace]
resolver = "3"
members = ["crates/*", "editors/zed"]
default-members = ["crates/roughly"]

[workspace.package]
version = "0.2.0-alpha.2"

[workspace.dependencies]
clap = { version = "4.5.40", features = ["derive"] }
console = "0.16.0"
ignore = "0.4.23"
indoc = "2.0.6"
itertools = "0.14.0"
ropey = "1.6.1"
serde = "1.0.219"
serde_json = "1.0.140"
similar = { version = "2.7.0", features = ["inline"] }
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = [
    "rt-multi-thread",
    "macros",
    "io-std",
    "time",
] }
toml = "0.8.23"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-tree = "0.4.0"
tree-sitter = "0.25.6"
# note: wait for https://github.com/r-lib/tree-sitter-r/pull/184 to get merged
# tree-sitter-r = "1.2.0"
tree-sitter-r = { git = "https://github.com/felix-andreas/tree-sitter-r", rev = "1e4506387a9373946566dd5cd63e71c09f05088e" }


# async-lsp
async-lsp = { version = "0.2.2", features = ["tokio"] }
tower = { version = "0.5.2" }
futures = { version = "0.3.31" }

# rofy
reedline = "0.40.0"
nu-ansi-term = "0.50.1"
extendr-api = "0.8.0"
extendr-engine = "0.8.0"

# dev-dependencies
insta = "1.43.1"
regex = "1.11.1"

# cfg(not(unix)) dependencies
tokio-util = { version = "0.7.15", features = ["compat"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
tree-sitter.opt-level = 3
tree-sitter-r.opt-level = 3

[profile.release]
strip = true
lto = true
