[package]
name = "roughly"
version = "0.0.4"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
console = "0.15.11"
dashmap = "6.1.0"
ignore = "0.4.23"
indoc = "2.0.6"
itertools = "0.14.0"
ropey = "1.6.1"
serde = "1.0.219"
similar = { version = "2.7.0", features = ["inline"] }
thiserror = "2.0.12"
tokio = { version = "1", features = [
	"rt-multi-thread",
	"macros",
	"io-std",
	"time",
] }
toml = "0.8.22"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-tree = "0.4.0"
tree-sitter = "0.25.4"
tree-sitter-r = "1.1.0"
# tree-sitter-r = { path = "../tree-sitter-r/" }

# tower-lsp
tower-lsp-server = { version = "0.21.1", optional = true }

# async-lsp
async-lsp = { version = "0.2.2", features = ["tokio"], optional = true }
tower = { version = "0.5.2", optional = true }
futures = { version = "0.3.31", optional = true }
reedline = "0.39.0"
nu-ansi-term = "0.50.1"
extendr-api = "0.8.0"
extendr-engine = "0.8.0"

[target.'cfg(not(unix))'.dependencies]
tokio-util = { version = "0.7.15", features = ["compat"] }

[dev-dependencies]
insta = "1.43.1"

[features]
default = ["async-lsp"]
async-lsp = ["dep:async-lsp", "dep:tower", "dep:futures"]
tower-lsp = ["dep:tower-lsp-server"]

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
tree-sitter.opt-level = 3
tree-sitter-r.opt-level = 3

[profile.release]
strip = true
lto = true
