[package]
name = "typing"
edition = "2024"
version.workspace = true

[lib]
name = "typing"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tree-sitter.workspace = true
tree-sitter-r.workspace = true

[dev-dependencies]
insta.workspace = true
