[package]
name = "typing"
edition = "2024"
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ropey.workspace = true
thiserror.workspace = true
tree-sitter.workspace = true
tree-sitter-r.workspace = true

[dev-dependencies]
fixtures = { path = "../fixtures" }
indoc.workspace = true
