[package]
name = "roughly"
version.workspace = true
edition = "2024"

[dependencies]
clap.workspace = true
console.workspace = true
ignore.workspace = true
indoc.workspace = true
itertools.workspace = true
ropey.workspace = true
serde.workspace = true
similar = { workspace = true, features = ["inline"] }
thiserror.workspace = true
tokio = { workspace = true, features = [
	"rt-multi-thread",
	"macros",
	"io-std",
	"time",
] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-tree.workspace = true
tree-sitter.workspace = true
tree-sitter-r.workspace = true

# async-lsp
async-lsp = { workspace = true, features = ["tokio"] }
tower = { workspace = true }
futures = { workspace = true }

[target.'cfg(not(unix))'.dependencies]
tokio-util = { workspace = true, features = ["compat"] }

[dev-dependencies]
insta.workspace = true

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
tree-sitter.opt-level = 3
tree-sitter-r.opt-level = 3

[profile.release]
strip = true
lto = true
