[package]
name = "differential"
edition = "2024"
version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/differential.rs"

[dependencies]
analysis-legacy = { path = "../analysis-legacy" }
semantics = { path = "../../crates/semantics" }
syntax = { path = "../../crates/syntax" }

[dev-dependencies]
salsa.workspace = true
format = { path = "../../crates/format" }
ide = { path = "../../crates/ide" }
ropey.workspace = true
roughly-legacy = { path = "../roughly-legacy" }
syntax = { path = "../../crates/syntax" }
