#!/usr/bin/env Rscript
# Regenerates types/<namespace>.exports — the vendored export manifests the
# stub loader uses to resolve names the typed corpus does not declare.
# Requires an R installation with the conditional packages available; run from
# the repository root: Rscript scripts/export-manifests.R
#
# Two kinds of namespace appear here. R's own namespaces and the packages with
# typed `.Rtypes` declarations need a manifest so that real exports outside the
# typed subset resolve instead of warning. The rest are manifest-ONLY: a widely
# used CRAN package with no typed declarations at all, whose manifest exists so
# that attaching it stops disabling unresolved-name detection project-wide — the
# export set becomes knowable, so a typo is a typo again, while every name from
# it types as `Unknown`.
namespaces <- c(
  "base", "stats", "utils", "graphics", "grDevices", "methods", "datasets",
  "tools", "parallel", "compiler", "grid", "splines", "stats4", "tcltk",
  "data.table", "dplyr", "ggplot2", "testthat",
  # Manifest-only, in rough order of how often R code attaches them.
  "tibble", "tidyr", "readr", "purrr", "stringr", "forcats", "lubridate",
  "magrittr", "rlang", "glue", "scales", "knitr", "jsonlite", "R6",
  # The meta-package needs its own manifest even though nearly every name it
  # offers comes from a member: without one, attaching it leaves its export set
  # unknowable, which is exactly what disables unresolved-name detection.
  "tidyverse"
)

exports_of <- function(namespace) {
  # `datasets` exports nothing through its namespace — its objects are lazy
  # data, visible through the attached search-path environment instead.
  if (namespace == "datasets") {
    ls("package:datasets", all.names = TRUE)
  } else {
    getNamespaceExports(namespace)
  }
}

write_manifest <- function(namespace, exports, note = NULL) {
  path <- file.path("types", paste0(namespace, ".exports"))
  # A manifest lists what R exports, so regenerating it on an OLDER R silently
  # drops the names newer versions added (`%||%` arrived in 4.4) and every use
  # of one becomes a false `unresolved`. The recorded version is the guard: an
  # existing manifest from a newer R is left alone and reported.
  recorded <- if (file.exists(path)) {
    sub(".*\\(R version ([0-9.]+).*", "\\1", readLines(path, n = 1))
  } else {
    NULL
  }
  if (!is.null(recorded) && getRversion() < recorded) {
    cat(sprintf(
      "skipped %s: its manifest records R %s, newer than this session's %s\n",
      namespace, recorded, getRversion()
    ))
    return(invisible())
  }
  header <- sprintf(
    "# Exports of the %s namespace (%s). Generated by scripts/export-manifests.R.",
    namespace, R.version.string
  )
  writeLines(
    c(header, note, sort(exports, method = "radix")),
    path
  )
}

for (namespace in namespaces) {
  write_manifest(namespace, exports_of(namespace))
}

# `tidyverse` is a meta-package: it re-exports almost nothing itself and instead
# ATTACHES its members, so its manifest alone would leave every `mutate` and
# `read_csv` unresolved. The loader handles that by activating a meta-package's
# members alongside it (`stubs::META_PACKAGE_MEMBERS`), which also gives a
# `library(tidyverse)` project dplyr's and ggplot2's *typed* declarations rather
# than a manifest's `Unknown`. This prints the membership R reports, so the
# hardcoded list can be checked against a live session.
before <- search()
suppressPackageStartupMessages(library(tidyverse))
attached <- sub("^package:", "", setdiff(search(), before))
cat(
  "library(tidyverse) attaches:",
  paste(sort(setdiff(attached, "tidyverse")), collapse = ", "), "\n"
)
