#!/usr/bin/env Rscript
# Regenerates types/<namespace>.exports — the vendored export manifests the
# stub loader uses to resolve names the typed corpus does not declare.
# Requires an R installation with data.table and dplyr available; run from
# the repository root: Rscript scripts/export-manifests.R
namespaces <- c(
  "base", "stats", "utils", "graphics", "grDevices", "methods", "datasets",
  "tools", "parallel", "compiler", "grid", "splines", "stats4", "tcltk",
  "data.table", "dplyr"
)
for (namespace in namespaces) {
  # datasets exports nothing through its namespace — its objects are lazy
  # data, visible through the attached search-path environment instead.
  exports <- if (namespace == "datasets") {
    ls("package:datasets", all.names = TRUE)
  } else {
    getNamespaceExports(namespace)
  }
  exports <- sort(exports, method = "radix")
  header <- sprintf(
    "# Exports of the %s namespace (%s). Generated by scripts/export-manifests.R.",
    namespace, R.version.string
  )
  writeLines(
    c(header, exports),
    file.path("types", paste0(namespace, ".exports"))
  )
}
